---

- name: Install glusterfs packages
  tags: never
  include_role:
    name: "geerlingguy.glusterfs"
  vars:
    glusterfs_ppa_version: "{{ gluster_repo_version }}"
    glusterfs_gpg_key_version: "{{ gluster_repo_version }}"

- name: Start gluster server
  service:
    name: "glusterd.service"
    state: started

- name: Create volumes
  import_tasks:
    - volume.yml
  loop: glusterfs_volumes

- name: Add peers
  gluster.gluster.gluster_peer:
    state: present
    nodes: glusterfs_peers
