---

- name: Install glusterfs packages
  tags: gluster_install
  include_role:
    name: "geerlingguy.glusterfs"
  vars:
    glusterfs_ppa_version: "{{ gluster_repo_version }}"
    glusterfs_gpg_key_version: "{{ gluster_repo_version }}"

- name: Enable management encryption
  copy:
    content: ''
    dest: /var/lib/glusterd/secure-access
  when: gluster_enable_tls_management
  register: _enabled_tls_managemnet

# If management encryption is enabled then the daemon needs to be restarted
- name: Restart gluster server
  tags: gluster_service
  service:
    name: "glusterd.service"
    state: restarted
  when: _enabled_tls_managemnet is defined and _enabled_tls_managemnet.changed

- name: Start gluster server
  tags: gluster_service
  service:
    name: "glusterd.service"
    state: started
  when: not _enabled_tls_managemnet is defined or not _enabled_tls_managemnet.changed

- name: Add peers
  tags: gluster_peers
  gluster.gluster.gluster_peer:
    state: present
    nodes: "{{ gluster_peers | default(groups[gluster_cluster_group] | difference([inventory_hostname]) | list ) }}"
  run_once: yes

- name: Create volumes
  tags: gluster_volumes
  include_tasks: "tasks/volume.yml"
  loop: "{{ gluster_volumes }}"
