---
- name: Converge
  hosts: all
  become: yes
  roles:
    - name: "Include haxwithaxe.gluster_cluster"
      role: "haxwithaxe.gluster_cluster"
      vars:
        gluster_repo_version: 11
        gluster_name: "docker-volumes"
        gluster_brick: "/bricks/docker-volumes"
        gluster_mount_point: "/mnt/docker-volumes"
        gluster_force: yes
        gluster_cluster_group: "production_swarm"
        gluster_volume_group: "docker"
