---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-0
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
    groups:
      - test_cluster
  - name: instance-1
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
    groups:
      - test_cluster
provisioner:
  name: ansible
verifier:
  name: ansible
